apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app-deployment
spec:
  selector:
    matchLabels:
      app: quarkus-app
  replicas: 1
  template:
    metadata:
      labels:
        app: quarkus-app
        version: 1.1.8
    spec:
      containers:
        - name: quarkus-app
          image: tiggel/ibm-quarkus-demo:1e620e68175e784a44cf41a0fda8897fd48e4a01
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockercreds
