apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app-deployment
spec:
  selector:
    matchLabels:
      app: quarkus-app
  replicas: 3
  template:
    metadata:
      labels:
        app: quarkus-app
        version: 1.1.8
    spec:
      containers:
        - name: quarkus-app
          image: tiggel/ibm-quarkus-demo:f3074176fa8cc013c933f6c82b5a4f2a666ccd70
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockercreds
