apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app-deployment
spec:
  selector:
    matchLabels:
      app: quarkus-app
  replicas: 3
  template:
    metadata:
      labels:
        app: quarkus-app
        version: 1.1.8
    spec:
      containers:
        - name: quarkus-app
          image: tiggel/ibm-quarkus-demo:4ead95bfa89ef972901c09fa19e54c11360424a4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockercreds
